// Valores del comboBox de ubicación
export const locationLabels = [
    { label: 'Nivel 1 Estante 1', status: "Nivel 1 Estante 1" },
    { label: 'Nivel 2 Estante 1', status: "Nivel 2 Estante 1" },
    { label: 'Nivel 3 Estante 1', status: "Nivel 3 Estante 1" },
    { label: 'Nivel 4 Estante 1', status: "Nivel 4 Estante 1" },
    { label: 'Nivel 1 Estante 2', status: "Nivel 1 Estante 2" },
    { label: 'Nivel 2 Estante 2', status: "Nivel 2 Estante 2" },
    { label: 'Nivel 3 Estante 2', status: "Nivel 3 Estante 2" },
    { label: 'Nivel 4 Estante 2', status: "Nivel 4 Estante 2" },
    { label: 'Nivel 1 Estante 3', status: "Nivel 1 Estante 3" },
    { label: 'Nivel 2 Estante 3', status: "Nivel 2 Estante 3" },
    { label: 'Nivel 3 Estante 3', status: "Nivel 3 Estante 3" },
    { label: 'Nivel 4 Estante 3', status: "Nivel 4 Estante 3" },
    { label: 'Nivel 5 Estante 3', status: "Nivel 5 Estante 3" },
    { label: 'Nivel 6 Estante 3', status: "Nivel 6 Estante 3" },
    { label: 'Caja de materiales a reparar o desechar', status: "Caja de materiales a reparar o desechar" },
    { label: 'Nivel 1 Estante 1A', status: "Nivel 1 Estante 1A" },
    { label: 'Nivel 2 Estante 1A', status: "Nivel 2 Estante 1A" },
    { label: 'Nivel 3 Estante 1A', status: "Nivel 3 Estante 1A" },
    { label: 'Nivel 1 Estante 2A', status: "Nivel 1 Estante 2A" },
    { label: 'Nivel 2 Estante 2A', status: "Nivel 2 Estante 2A" },
    { label: 'Nivel 3 Estante 2A', status: "Nivel 3 Estante 2A" },
    { label: 'Nivel 4 Estante 2A', status: "Nivel 4 Estante 2A" },
    { label: 'Nivel 1 Estante 3A', status: "Nivel 1 Estante 3A" },
    { label: 'Nivel 2 Estante 3A', status: "Nivel 2 Estante 3A" },
    { label: 'Nivel 3 Estante 3A', status: "Nivel 3 Estante 3A" },
    { label: 'Nivel 4 Estante 3A', status: "Nivel 4 Estante 3A" },
    { label: 'Nivel 5 Estante 3A', status: "Nivel 5 Estante 3A" },
    { label: 'Nivel 1 Estante 4A', status: "Nivel 1 Estante 4A" },
    { label: 'Nivel 2 Estante 4A', status: "Nivel 2 Estante 4A" },
    { label: 'Nivel 3 Estante 4A', status: "Nivel 3 Estante 4A" },
    { label: 'Nivel 4 Estante 4A', status: "Nivel 4 Estante 4A" },
    { label: 'Nivel 5 Estante 4A', status: "Nivel 5 Estante 4A" },
    { label: 'Nivel 1 Estante 5A', status: "Nivel 1 Estante 5A" },
    { label: 'Nivel 2 Estante 5A', status: "Nivel 2 Estante 5A" },
    { label: 'Nivel 3 Estante 5A', status: "Nivel 3 Estante 5A" },
    { label: 'Nivel 4 Estante 5A', status: "Nivel 4 Estante 5A" },
    { label: 'Nivel 5 Estante 5A', status: "Nivel 5 Estante 5A" },
    { label: 'Nivel 6 Estante 5A', status: "Nivel 6 Estante 5A" },
    { label: 'Nivel 7 Estante 5A', status: "Nivel 7 Estante 5A" },
    { label: 'Nivel 8 Estante 5A', status: "Nivel 8 Estante 5A" },
    { label: 'Nivel 9 Estante 5A', status: "Nivel 9 Estante 5A" },
    { label: 'Nivel 10 Estante 5A', status: "Nivel 10 Estante 5A" },
    { label: 'Nivel 11 Estante 5A', status: "Nivel 11 Estante 5A" },
    { label: 'Nivel 12 Estante 5A', status: "Nivel 12 Estante 5A" },
    { label: 'Nivel 13 Estante 5A', status: "Nivel 13 Estante 5A" },
    { label: 'Nivel 14 Estante 5A', status: "Nivel 14 Estante 5A" },
    { label: 'Nivel 1 Estante 6A', status: "Nivel 1 Estante 6A" },
    { label: 'Nivel 2 Estante 6A', status: "Nivel 2 Estante 6A" },
    { label: 'Nivel 3 Estante 6A', status: "Nivel 3 Estante 6A" },
    { label: 'Nivel 4 Estante 6A', status: "Nivel 4 Estante 6A" },
    { label: 'Nivel 5 Estante 6A', status: "Nivel 5 Estante 6A" },
    { label: 'Nivel 6 Estante 6A', status: "Nivel 6 Estante 6A" },
    { label: 'Nivel 7 Estante 6A', status: "Nivel 7 Estante 6A" },
    { label: 'Nivel 8 Estante 6A', status: "Nivel 8 Estante 6A" },
    { label: 'Nivel 9 Estante 6A', status: "Nivel 9 Estante 6A" },
    { label: 'Nivel 10 Estante 6A', status: "Nivel 10 Estante 6A" },
    { label: 'Nivel 11 Estante 6A', status: "Nivel 11 Estante 6A" },
    { label: 'Nivel 12 Estante 6A', status: "Nivel 12 Estante 6A" },
    { label: 'Nivel 1 Estante 7A', status: "Nivel 1 Estante 7A" },
    { label: 'Nivel 2 Estante 7A', status: "Nivel 2 Estante 7A" },
    { label: 'Nivel 3 Estante 7A', status: "Nivel 3 Estante 7A" },
    { label: 'Nivel 4 Estante 7A', status: "Nivel 4 Estante 7A" },
    { label: 'Nivel 5 Estante 7A', status: "Nivel 5 Estante 7A" },
    { label: 'Nivel 6 Estante 7A', status: "Nivel 6 Estante 7A" },
    { label: 'Nivel 7 Estante 7A', status: "Nivel 7 Estante 7A" },
    { label: 'Nivel 8 Estante 7A', status: "Nivel 8 Estante 7A" },
    { label: 'Nivel 9 Estante 7A', status: "Nivel 9 Estante 7A" },
    { label: 'Nivel 10 Estante 7A', status: "Nivel 10 Estante 7A" },
    { label: 'Nivel 11 Estante 7A', status: "Nivel 11 Estante 7A" },
    { label: 'Nivel 12 Estante 7A', status: "Nivel 12 Estante 7A" },
    { label: 'Laboratorio', status: "Laboratorio" },
    { label: 'Almacén', status: "Almacén" },
  ];

   // Valores del comboBox de marcas
   export const brandLabels = [
    { label: 'QVF', status: "QVF"},
    { label: 'Pyrex', status: "Pyrex"},
    { label: 'Hirschmann EM-Techcolor', status: "Hirschmann EM-Techcolor"},
    { label: 'Kimax', status: "Kimax"},
    { label: 'Sin información', status: "Sin información"},
    { label: 'N/A', status: "N/A"},
    { label: 'Fisher', status: "Fisher"},
    { label: 'Pobel', status: "Pobel"},
    { label: 'tecno fuego', status: "tecno fuego"},
    { label: 'PDV', status: "PDV"},
    { label: 'Venoco', status: "Venoco"},
    { label: 'Electrothermal', status: "Electrothermal"},
    { label: 'GLASS-COL APPARATUS', status: "GLASS-COL APPARATUS"},
    { label: 'Electromantle', status: "Electromantle"},
    { label: 'Guardian', status: "Guardian"},
    { label: 'Q-VAR', status: "Q-VAR"},
    { label: 'Kao Clorex', status: "Kao Clorex"},
    { label: 'CPP Sediment', status: "CPP Sediment"},
    { label: 'Pall Trinity Micro Corporation', status: "Pall Trinity Micro Corporation"},
    { label: 'Champion', status: "Champion"},
    { label: 'Whatman', status: "Whatman"},
    { label: 'Union Carbide', status: "Union Carbide"},
    { label: 'SMC', status: "SMC"},
    { label: 'INCA', status: "INCA"},
    { label: 'PMC', status: "PMC"},
    { label: 'Corning', status: "Corning"},
    { label: 'Sartorius', status: "Sartorius"},
    { label: 'Thermolyne', status: "Thermolyne"},
    { label: 'Chaus', status: "Chaus"},
    { label: 'Trygon', status: "Trygon"},
    { label: 'Acmeter', status: "Acmeter"},
    { label: 'BUCHI', status: "BUCHI"},
    { label: 'Lab crest', status: "Lab crest"},
    { label: 'Tinius Olsen', status: "Tinius Olsen"},
    { label: 'Hamilton', status: "Hamilton"},
    { label: 'Brady', status: "Brady"},
    { label: 'MEGO AFEK', status: "MEGO AFEK"},
    { label: 'ASHCROFT', status: "ASHCROFT"},
    { label: 'Bourdon', status: "Bourdon"},
    { label: 'Parr', status: "Parr"},
    { label: 'DIN', status: "DIN"},
    { label: 'INDUPARTS', status: "INDUPARTS"},
    { label: 'FTB', status: "FTB"},
    { label: 'ENFM', status: "ENFM"},
    { label: 'OhmE', status: "OhmE"},
    { label: 'WEIS', status: "WEIS"},
    { label: 'Brooks Instrument', status: ""},
    { label: 'Brooks Instrument', status: "Brooks Instrument"},
    { label: 'Harris', status: "Harris"},
    { label: 'Alear', status: "Alear"},
    { label: 'National Cylinder Gas', status: "National Cylinder Gas"},
    { label: 'Uniweld', status: "Uniweld"},
    { label: 'USG', status: "USG"},
    { label: 'Messer', status: "Messer"},
    { label: 'Linde Gas', status: "Linde Gas"},
    { label: 'PRAXAIR', status: "PRAXAIR"},
    { label: 'AGA', status: "AGA"},
    { label: 'Whitey', status: "Whitey"},
    { label: 'Swagelok', status: "Swagelok"},
    { label: 'Hoke', status: "Hoke"},
    { label: 'Dynisco', status: "Dynisco"},
    { label: 'Forney', status: "Forney"},
    { label: 'Parker', status: "Parker"},
    { label: 'Detroit', status: "Detroit"},
    { label: 'Pall', status: "Pall"},
  ];

     // Valores del comboBox de capacidad
     export const capacityLabels = [
        { label: '8000 ml', status: "8000 ml" },
        { label: '5000 ml', status: "5000 ml" },
        { label: '2000 ml', status: "2000 ml" },
        { label: '1500 ml', status: "1500 ml" },
        { label: '1000 ml', status: "1000 ml" },
        { label: '600 ml', status: "600 ml" },
        { label: '500 ml', status: "500 ml" },
        { label: '400 ml', status: "400 ml" },
        { label: '250 ml', status: "250 ml" },
        { label: '225ml', status: "225ml" },
        { label: '125 ml', status: "125 ml" },
        { label: '100 ml', status: "100 ml" },
        { label: '50 ml', status: "50 ml" },
        { label: '25 ml', status: "25 ml" },
        { label: '10 ml', status: "10 ml" },
        { label: '5 ml', status: "5 ml" },
        { label: '1 ml', status: "1 ml" },
        { label: 'N/A', status: "N/A" },
        { label: '55 gal', status: "55 gal" },
        { label: '150 kg', status: "150 kg" },
        { label: '1520 kg', status: "1520 kg" },
        { label: '3,79 l', status: "3,79 l" },
        { label: 'Sin información', status: "Sin información" },
        { label: '37 m', status: "37 m" },
        { label: '1 m', status: "1 m" },
        { label: '90', status: "90" },
        { label: '25 kg', status: "25 kg" },
        { label: '1 hp', status: "1 hp" },
        { label: '19 l', status: "19 l" },
        { label: '40 cm', status: "40 cm" },
        { label: '50 cm', status: "50 cm" },
        { label: '1 Amp', status: "1 Amp" },
        { label: '100 °C', status: "100 °C" },
        { label: ' 10 micro l', status: " 10 micro l" },
        { label: ' 5 micro l', status: " 5 micro l" },
        { label: '1 micro l', status: "1 micro l" },
        { label: '24 kg', status: "24 kg" },
        { label: '20 kg', status: "20 kg" },
     ]