const TeachersInformation = [
    {
        name: "Sergio David Rosales Anzola",
        imageURL: "https://firebasestorage.googleapis.com/v0/b/metrolabsing.appspot.com/o/teachers%2FteacherSergio.png?alt=media&token=ef2fe670-f079-4f61-837b-ad25419cfb4e&_gl=1*1dlvnji*_ga*Njg5Mzg4MDQuMTY4MTk0MTMzMw..*_ga_CW55HF8NVT*MTY5ODYxMTcyOS43OS4xLjE2OTg2MTIxNTguNTcuMC4w",
        education:" • Doctorado en Física, Instituto Venezolano de Investigaciones Científicas (IVIC)\n • Ingeniero Químico, Universidad Nacional Experimental Politécnica “Antonio José de Sucre” (UNEXPO)\n\nEl Dr.Sergio D. Rosales-Anzola es ingeniero químico graduado de la Universidad Nacional Experimental Politécnica “Antonio José de Sucre” (UNEXPO) y cuenta con un doctorado en Física del Instituto Venezolano de Investigaciones Científicas (IVIC).",
        email: "srosales@unimet.edu.ve",
        interestAreas: "Las áreas de interés en investigación incluyen surfactantes, sinergia en mezclas de surfactantes, fenómenos interfaciales, reología interfacial dilatacional, reometría de corte continuo y oscilatorio, viscoelasticidad de fluidos, estabilidad de espumas, interacción polímero-surfactante y el diseño de aplicaciones y uso de realidad aumentada para la enseñanza en educación en ingeniería.",
        asignatures: "• Mecánica de Fluidos\n• Laboratorio de fluidos y transferencias\n• Principios de procesos industriales II",
        // publications: "• Rosales-Anzola, S., Perez-Hernandez, M., “Engineering education applications”. HUMAN REVIEW, 2023, pp. 2 – 17. doi.org/10.37467/revhuman.v12.4688.\n • Quintero, F., González, J., Arellano, J., Rosales-Anzola, S. D., “Formation Of Tribofilms From Surfactants With Different Degrees Of Ethoxylation On Steel Surfaces In Boundary Lubrication Regime”, in Surfactants in Tribology, Vol 5, Chapter 9. Biresaw, G., y Mittal, K. (Eds.), CRC Press, Taylor & Francis Group, 2017. ISBN 9781498734790.",
    },
    {
        name: "Miguel Manuel Pérez Hernández",
        imageURL: "https://firebasestorage.googleapis.com/v0/b/metrolabsing.appspot.com/o/teachers%2FteacherMiguel.png?alt=media&token=65ae57be-b78e-4a54-9468-d7f8c3efa20c&_gl=1*yd90bx*_ga*Njg5Mzg4MDQuMTY4MTk0MTMzMw..*_ga_CW55HF8NVT*MTY5ODYxMTcyOS43OS4xLjE2OTg2MTI2NTMuMTEuMC4w",
        education: "• Licenciatura en Química, Opción Tecnológica – Universidad Simón Bolívar, Venezuela.\n• Homologado al título universitario oficial español de Licenciado en Química.\n• Diploma de Estudios Avanzados (DEA), (Físico-Química), Universidad de Borgoña, Dijon, Francia.\n• Doctor de Tercer Ciclo, Especialidad Físico-Química, Universidad de Borgoña, Dijon, Francia.\n\nCuenta con más de 28 años de experiencia como profesor universitario en el área de ingeniería química, autor de artículos en revistas arbitradas, asistencias a congresos, simposios, conferencias, coloquios y seminarios relacionados en el área de corrosión, pinturas industriales, obtención y evaluación de carbón activado, evaluación de tintas naturales, reparación y modernización de laboratorios de ingeniería de forma sostenible, desarrollo de un laboratorio de instrumentación y desarrollo de prácticas de laboratorio virtuales utilizando herramientas de simulación (Matlab-Symulink).",
        email: "mperez@unimet.edu.ve",
        interestAreas: "Proyectos de investigación en el área de: Desarrollo de un Laboratorio de Instrumentación; Diseño, construcción de un potenciostato/galvanostato de bajo costo para aplicaciones analíticas y educativas en la Universidad Metropolitana.",
        asignatures: "• Reactores\n• Laboratorio de procesos de separación\n• Laboratorio de fluidos y transferencias\n• Principios de procesos industriales",
        // publications: "• Coconut shell charcoal adsorption to remove methyl orange in aqueous solutions. Isabel C. Páez-Pumar Romer, Isabella V. Plazola Santana, Rosa M. Rodríguez Bengoechea, Miguel M. Pérez Hernández. Universidad Metropolitana, Venezuela. Publicado 05/04/2022. DOI: 10.5772/intechopen.102898 \n • Simulación de un proceso de filtración para el laboratorio de procesos de separación de la Universidad Metropolitana. W. Rauch, R. Rodríguez, M. Pérez, Publicado el 10/03/2022, Revista TEKHNÉ (UCAB), No. 25.1. ISSN: electrónico: 2790-5195. https://revistasenlinea.saber.ucab.edu.ve/index.php/tekhne/article/view/5442 \n Simulación de una práctica de fluidización para el laboratorio de procesos de separación de la Universidad Metropolitana. Da Silva, A., Segura, D., Toledo, M., & Pérez, M. Publicado el 07/04/2022. Revista TEKHNÉ (UCAB), 25(2). https://revistasenlinea.saber.ucab.edu.ve/index.php/tekhne/article/view/5137/4977 \n• Mecanismo coagulacion- floculacion, utilizando alumbre comercial y alumbre preparado a partir de material de reciclaje. Comparación de la eficiencia. Universidad Metropolitana. Rosa María Rodríguez, Nancy Confortti, Miguel Pérez, Sashenka Suárez, Daniela Lobo. Revista Producción + Limpia. Vol. 17 Núm. 1 (2022). https://doi.org/10.22507/10.22507/pml.v17n1a4 \n • Development of virtual laboratories in engineering with the participation of undergraduate students. Pérez Hernández, M. M. (2022). HUMAN REVIEW. International Humanities Review / Revista Internacional De Humanidades, 15(3), 1–12. https://doi.org/10.37467/revhuman.v11.4239 \n• Elaboración de carbón activado a partir de endocarpio de coco para la remoción de naranja de metilo en fase acuosa. Revista Internacional de Contaminación Ambiental. México. Miguel Zambrano; Miguel M. Pérez H. Publicado el 21 Feb. 2023. DOI: https://doi.org/10.20937/RICA.54514 \n • Engineering education applications. Rosales-Anzola, S. D., & Pérez-Hernández, M. M. (2023). HUMAN REVIEW. International Humanities Review / Revista Internacional De Humanidades, 16(5), 1–17. https://doi.org/10.37467/revhuman.v12.4688 \n • Elaboración de Etanol industrial de cáscara de banana (Musa paradisiaca): Perez Hernandez, M. M., Lander Bautista, L. G., & Taborda Nieto, D. (2023). Tekhné, 26(2), 13–21. Recuperado a partir de https://revistasenlinea.saber.ucab.edu.ve/index.php/tekhne/article/view/6174",
    },
    {
        name: "Juan Bernardo Tovar Salas",
        imageURL: "https://firebasestorage.googleapis.com/v0/b/metrolabsing.appspot.com/o/teachers%2FteacherTovar.png?alt=media&token=1c676131-2d56-4afe-8e7f-f3c220110e03&_gl=1*1f8s13o*_ga*Njg5Mzg4MDQuMTY4MTk0MTMzMw..*_ga_CW55HF8NVT*MTY5ODYxMTcyOS43OS4xLjE2OTg2MTI2MzEuMzMuMC4w",
        education: "Ha tenido una participación activa en diversos proyectos de investigación llevados a cabo en el Laboratorio de Electroquímica de la Universidad Simón Bolívar (USB). En la actualidad, adelanta en el Laboratorio de Procesos de Separación (Unimet), diversos proyectos en el área de la instrumentación. Está a cargo del Laboratorio de Máquinas Eléctricas (Unimet).",
        email: "juantovar@correo.unimet.edu.ve",
        interestAreas: "Busco soluciones tecnológicas y sustentables a problemas actuales desde la electroquímica. Mis áreas de interés son la Electroquímica, el Almacenamiento y Conversión de Energía, Sensores, Instrumentación, Control, Electrónica de Potencia, Tratamiento de agua y Electromagnetismo.",
        asignatures: "• Arquitectura del Computador\n• Laboratorio correspondiente a la materia Redes Eléctricas II\n• Laboratorio correspondiente a la materia Electromecánica\n• Laboratorio correspondiente a la materia Máquinas Eléctricas I\n• Laboratorio correspondiente a la materia Máquinas Eléctricas II",
        // publications: "No posee",
    },
    {
        name: "Jose Barriola",
        imageURL: "https://firebasestorage.googleapis.com/v0/b/metrolabsing.appspot.com/o/teachers%2FteacherBarriola.png?alt=media&token=7ceb3e78-37fc-4509-847f-0b0db9de13a9&_gl=1*1e9nstt*_ga*Njg5Mzg4MDQuMTY4MTk0MTMzMw..*_ga_CW55HF8NVT*MTY5ODYxMTcyOS43OS4xLjE2OTg2MTI2NjQuNjAuMC4w",
        education: "• Ingeniero Electricista graduado en la Universidad central de Venezuela el año 1973.\n\nLaboro durante quince (15) años en OPSIS (Sistema Eléctrico Interconectado Nacional), luego de ello laboro durante diez años como Gerente de la compañía Controles Texas del Grupo Inelectra, dedicado a la automatización y control, estando luego trabajando durante 20 años en Honeywell, iniciándose como Gte de Ingeniería, siendo los últimos años el vicepresidente ejecutivo (2018), Para luego dedicarse exclusivamente a la educación superior en la Universidad Metropolitana, habiendo estado impartiendo clases en la Universidad Central de Venezuela durante los últimos 19 años.",
        email: "jbarriola@unimet.edu.ve",
        interestAreas: "El mayor interés y dedicación es en lo referente al control de Procesos, automatizando y actualizando tecnológicamente los distintos laboratorios de procesos de la universidad, así como al desarrollo de la Mecatrónica y la robótica.",
        asignatures: "• Electrónica 1\n• Redes 2 \n•  Electromecánica \n • Electrónica Industrial \n • Automatización y control \n • Control de Procesos",
        // publications: "No posee",
    },
]

export default TeachersInformation;